name: NodeJS with Webpack
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  wait:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: __application
          start: npm run storybook
          wait-on: 'http://localhost:6006'
